### ISSUE TITLE
renaming

### ISSUE THREAD

**Issue by samoht** [mirage/charrua#69]
Would it be possible to:
1. rename the repository to `charrua` 
2. rename the core library to `charrua`

Not sure that `-core` is needed anymore. WDYT?

**Comment by yomimono** [comment]
I have no opinion on the name (and will not rename the package myself), but I strongly desire that anyone who renames it also handles the renaming for reverse dependencies, submits the necessary pull requests to `opam-repository`, and handles the change in the `mirage` front-end tool.

**Comment by haesbaert** [comment]
This has been agreed already, but we would change to charrua-dhcp.

Core makes no sense anymore indeed.

**Comment by yomimono** [comment]
Aw, c'mon.  `charrua-core` is like `normcore` or `thrashcore` or `hardcore`, but better.  It makes total sense.

**Comment by haesbaert** [comment]
Hobbocore forevis !

**Comment by haesbaert** [comment]
Also I'd like the renaming to make 1.0, where charrua-client would be also merged into charrua-dhcp, as Dhcp_client (lib/client.ml), so that it becomes symetrical with the server.

what do you think @yomimono ?

**Comment by yomimono** [comment]
> I have no opinion on the name (and will not rename the package myself), but I strongly desire that anyone who renames it also handles the renaming for reverse dependencies, submits the necessary pull requests to opam-repository, and handles the change in the mirage front-end tool.

Renaming the package will break compatibility and so makes sense to do at version 1.0.

**Comment by hannesm** [comment]
now 1.5 years passed, and there has been lots of activity on this repository... I'm in favour of fixing this issue, but am not entirely sure what the best way forward is, here's my proposal:
- repository should be `charrua`
- move the `server` logic (dhcp_server.ml) be moved to a `server` directory (providing `charrua-server` -- a separate opam package and ocamlfind lib)
- move the dhcp config file parser to another opam package (parser? config?) and separate directory

now, since it's rather convenient (due to lack of namespacing) in ocaml/opam to use the opam package name as prefix of the modules, I'd also be in favour of renaming the modules in here:
- lib/dhcp_wire to lib/charrua
- etc.

any opinion on this?  if not (or positive), I'd try to open a PR that accomplishes the stuff mentioned above, and we can see whether you like it or not.

**Comment by hannesm** [comment]
done in #100, merged. repository is also renamed. release upcoming
